#
# Macro file for the initialization phase of "NeutronShielding.cc"
# when runing in interactive mode
#
# Sets some default verbose
#
/control/verbose 0
/run/verbose 0
/run/particle/verbose 0
/process/verbose 0
/NS/verbose/doOutputStep false
#
# Update detector after setting some things
/NS/det/update
#
# Use this open statement to create an OpenGL view:
#/vis/open OGL 1200x800-0+0
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
#/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Specify view: 
/vis/viewer/set/upVector 1
/vis/viewer/set/viewpointThetaPhi 70. 225.
/vis/viewer/set/hiddenEdge 0 
#
# Specify zoom value:
/vis/viewer/zoom 1.1
#
# Specify style (surface or wireframe):
#/vis/viewer/set/style wireframe
#
# Draw coordinate axes:
#/vis/scene/add/axes 0 0 0 1 m
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
#/vis/scene/add/hits
#
# To draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set e- blue
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
#/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
#

/NS/gen/genEvaporation 0
/NS/gen/particleEnergy 10.0
/run/beamOn 100000
/NS/gen/particleEnergy 9.8 
/run/beamOn 100000
/NS/gen/particleEnergy 9.6 
/run/beamOn 100000
/NS/gen/particleEnergy 9.4 
/run/beamOn 100000
/NS/gen/particleEnergy 9.2 
/run/beamOn 100000
/NS/gen/particleEnergy 9.0
/run/beamOn 100000
/NS/gen/particleEnergy 8.8 
/run/beamOn 100000
/NS/gen/particleEnergy 8.6 
/run/beamOn 100000
/NS/gen/particleEnergy 8.4 
/run/beamOn 100000
/NS/gen/particleEnergy 8.2 
/run/beamOn 100000
/NS/gen/particleEnergy 8.0 
/run/beamOn 100000
/NS/gen/particleEnergy 7.8 
/run/beamOn 100000
/NS/gen/particleEnergy 7.6 
/run/beamOn 100000
/NS/gen/particleEnergy 7.4 
/run/beamOn 100000
/NS/gen/particleEnergy 7.2 
/run/beamOn 100000
/NS/gen/particleEnergy 7.0 
/run/beamOn 100000
/NS/gen/particleEnergy 6.8 
/run/beamOn 100000
/NS/gen/particleEnergy 6.6 
/run/beamOn 100000
/NS/gen/particleEnergy 6.4 
/run/beamOn 100000
/NS/gen/particleEnergy 6.2 
/run/beamOn 100000
/NS/gen/particleEnergy 6.0 
/run/beamOn 100000
/NS/gen/particleEnergy 5.8 
/run/beamOn 100000
/NS/gen/particleEnergy 5.6 
/run/beamOn 100000
/NS/gen/particleEnergy 5.4 
/run/beamOn 100000
/NS/gen/particleEnergy 5.2 
/run/beamOn 100000
/NS/gen/particleEnergy 5.0
/run/beamOn 100000
/NS/gen/particleEnergy 4.8 
/run/beamOn 100000
/NS/gen/particleEnergy 4.6 
/run/beamOn 100000
/NS/gen/particleEnergy 4.4 
/run/beamOn 100000
/NS/gen/particleEnergy 4.2 
/run/beamOn 100000
/NS/gen/particleEnergy 4.0 
/run/beamOn 100000
/NS/gen/particleEnergy 3.8 
/run/beamOn 100000
/NS/gen/particleEnergy 3.6 
/run/beamOn 100000
/NS/gen/particleEnergy 3.4 
/run/beamOn 100000
/NS/gen/particleEnergy 3.2 
/run/beamOn 100000
/NS/gen/particleEnergy 3.0 
/run/beamOn 100000
/NS/gen/particleEnergy 2.8 
/run/beamOn 100000
/NS/gen/particleEnergy 2.6 
/run/beamOn 100000
/NS/gen/particleEnergy 2.4 
/run/beamOn 100000
/NS/gen/particleEnergy 2.2 
/run/beamOn 100000
/NS/gen/particleEnergy 2.0 
/run/beamOn 100000
/NS/gen/particleEnergy 1.8 
/run/beamOn 100000
/NS/gen/particleEnergy 1.6 
/run/beamOn 100000
/NS/gen/particleEnergy 1.4 
/run/beamOn 100000
/NS/gen/particleEnergy 1.2 
/run/beamOn 100000
/NS/gen/particleEnergy 1.0 
/run/beamOn 100000
/NS/gen/particleEnergy 0.8 
/run/beamOn 100000
/NS/gen/particleEnergy 0.6 
/run/beamOn 100000
/NS/gen/particleEnergy 0.4 
/run/beamOn 100000
/NS/gen/particleEnergy 0.2 
/run/beamOn 100000
